services:
  - type: web
    name: portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s build
    envVars:
      - key: NODE_ENV
        value: production
